#!/usr/bin/env python3
"""Pick 4 random grid intersections, emit a runtime competition SDF + yaml.

The mission rules call for 4 ArUco markers placed at grid intersections with
positions disclosed at competition time. This script is the pre-launch step
that materializes a fresh layout each sim run.

It reads the marker-less template ``competition.sdf`` from the world share
directory, injects 4 ``<model name="aruco_<id>">`` blocks before
``</world>``, and writes the result to ``competition_runtime.sdf`` in the
same share directory (gitignored via the install/build dirs). It also
overwrites ``aruco_layout.yaml`` so any consumer using the runtime layout
sees the same 4 coordinates.

Official spec (2026-07 survey notice): markers sit on interior grid
vertices ("외곽선에 배치 안함"), 3 m cells, IDs are 4 UNIQUE values from
0..49. Inner intersections of the 30 x 21 m arena:
  x in {3, 6, ..., 27} m  (9 columns)
  y in {3, 6, ..., 18} m  (6 rows)
"""
from __future__ import annotations

import argparse
import os
import random
import sys
import time


# Inner grid intersections; matches the 3m-cell layout in world/textures/floor.png.
GRID_X = [3.0, 6.0, 9.0, 12.0, 15.0, 18.0, 21.0, 24.0, 27.0]
GRID_Y = [3.0, 6.0, 9.0, 12.0, 15.0, 18.0]
NUM_MARKERS = 4
ID_RANGE = 50           # rules: 4 unique IDs from 0..49
MARKER_SIZE = 0.4       # rules: 0.4 m x 0.4 m sheet (white bg, black code)

MARKER_BLOCK_TEMPLATE = """    <model name="aruco_{id}">
      <static>true</static>
      <pose>{x} {y} 0.001 0 0 0</pose>
      <link name="link">
        <visual name="visual">
          <pose>0 0 0.001 0 0 0</pose>
          <geometry>
            <plane>
              <normal>0 0 1</normal>
              <size>{size} {size}</size>
            </plane>
          </geometry>
          <material>
            <ambient>1 1 1 1</ambient>
            <diffuse>1 1 1 1</diffuse>
            <pbr>
              <metal>
                <albedo_map>model://world_assets/textures/aruco_{id}.png</albedo_map>
                <metalness>0.0</metalness>
                <roughness>0.9</roughness>
              </metal>
            </pbr>
          </material>
        </visual>
      </link>
    </model>
"""

INJECT_MARKER = "<!-- MARKER_BLOCK_INJECTION_POINT -->"


def pick_markers(seed: int) -> list[tuple[int, float, float]]:
    rng = random.Random(seed)
    intersections = [(x, y) for x in GRID_X for y in GRID_Y]
    chosen = rng.sample(intersections, NUM_MARKERS)
    # Rules: 4 unique ArUco IDs anywhere in 0..49 — texture files
    # aruco_0.png .. aruco_49.png must all exist (aruco.py --ids 0-49).
    ids = rng.sample(range(ID_RANGE), NUM_MARKERS)
    return [(mid, x, y) for mid, (x, y) in zip(ids, chosen)]


def render_marker_blocks(markers: list[tuple[int, float, float]]) -> str:
    return "".join(
        MARKER_BLOCK_TEMPLATE.format(id=mid, x=x, y=y, size=MARKER_SIZE)
        for mid, x, y in markers
    )


def render_runtime_sdf(template_text: str, marker_blocks: str) -> str:
    if INJECT_MARKER in template_text:
        return template_text.replace(INJECT_MARKER, marker_blocks)
    # Fallback: inject before </world>.
    end_tag = "</world>"
    idx = template_text.rfind(end_tag)
    if idx == -1:
        raise RuntimeError(
            "competition.sdf has neither INJECT_MARKER comment nor </world>"
        )
    return template_text[:idx] + marker_blocks + template_text[idx:]


def render_yaml(markers: list[tuple[int, float, float]]) -> str:
    lines = [
        "# ArUco marker layout — generated by marker_randomize.py.",
        "# Do not edit by hand; the next sim launch overwrites this file.",
        "",
        f"marker_size: {MARKER_SIZE}",
        "marker_thickness: 0.002",
        "texture_dir: textures",
        "",
        "markers:",
    ]
    for mid, x, y in markers:
        lines.append(f"  - id: {mid}")
        lines.append(f"    pose: [{x}, {y}, 0.001, 0.0, 0.0, 0.0]")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--seed", type=int, default=-1,
                    help="Random seed. -1 picks from time().")
    ap.add_argument("--share-dir", required=True,
                    help="Path to share/world (provided by the launcher).")
    args = ap.parse_args()

    seed = args.seed if args.seed >= 0 else int(time.time())

    markers = pick_markers(seed)

    template_path = os.path.join(args.share_dir, "worlds", "competition.sdf")
    if not os.path.exists(template_path):
        print(f"ERROR: template not found at {template_path}", file=sys.stderr)
        return 1
    with open(template_path, "r", encoding="utf-8") as fp:
        template_text = fp.read()

    marker_blocks = render_marker_blocks(markers)
    runtime_sdf = render_runtime_sdf(template_text, marker_blocks)

    out_sdf = os.path.join(args.share_dir, "worlds", "competition_runtime.sdf")
    out_yaml = os.path.join(args.share_dir, "config", "aruco_layout.yaml")

    os.makedirs(os.path.dirname(out_sdf), exist_ok=True)
    os.makedirs(os.path.dirname(out_yaml), exist_ok=True)

    with open(out_sdf, "w", encoding="utf-8") as fp:
        fp.write(runtime_sdf)
    with open(out_yaml, "w", encoding="utf-8") as fp:
        fp.write(render_yaml(markers))

    print(
        f"marker_randomize: seed={seed} markers="
        + ", ".join(f"({mid}: {x:.1f}, {y:.1f})" for mid, x, y in markers)
    )
    print(f"  -> {out_sdf}")
    print(f"  -> {out_yaml}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
